list_servers_private_ips = "<K3S_SERVERS_PRIVATE_IPS>"
list_servers_public_ips  = "<K3S_SERVERS_PUBLIC_IPS>"
ssh_user                 = "<SSH_USER>"
ssh_private_key          = "<SSH_PRIVATE_KEY_PATH>"
servers_args             = "<K3S_SERVERS_ARGS>"
